name: VarsYSecretos

on:
  workflow_dispatch:

jobs:
  probando_secretos:
    name: Probar secretos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secreto del token 
        run: echo ${{ secrets.SONAR_TOKEN }}
      - name: Secreto en json
        run: echo ${{ secrets.SECRETO_JS }}
      - name: Variables
        run: echo ${{ vars.SONAR_HOST_URL }}        
